name: Build C++ Program

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
      - name: Install packages
        run: |
          pacman -S mingw-w64-x86_64-gcc
          pacman -S mingw-w64-x86_64-make