name: Build C++ Program

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Set up MSYS2 and install dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-gsl mingw-w64-x86_64-openmp
          release: true
      - uses: actions/checkout@v2
      - name: Build using make
        run: |
          cd ${{github.workspace}}
          make
      - name: Run program
        run: |
          dir "${{github.workspace}}/build"
          "${{github.workspace}}/build/main.exe"