name: Build C++ Program

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Chocolatey
      run: |
        sudo apt-get install -y dirmngr gnupg apt-transport-https software-properties-common
        sudo apt-key adv --keyserver hkps://keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
        echo "deb https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list
        sudo apt-get update
        sudo apt-get install -y gh
        gh auth login --web
        gh config set prompt disabled
        sudo apt-get install -y chocolatey
    
    - name: Install MSYS2
      run: |
        choco install msys2 -y
        refreshenv
        
    - name: Install required packages with MSYS2
      run: |
        packman --noconfirm -S mingw-w64-x86_64-gcc mingw-w64-x86_64-gsl mingw-w64-x86_64-openmp
    
    - name: Build C++ program with g++
      run: |
        g++ -g ./src/*.cpp -o main.exe -lgsl -lgslcblas -lm -fopenmp
        
    - name: Run C++ program
      run: |
        ./main.exe
