name: Build C++ Program

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      # - name: Compile C++ program
      #   run: g++ -o main src/main.cpp

      - uses: msys2/setup-msys2@v2
        with:
          location: D:\
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          # install GCC, GSL and OpenMP
          msys2 -c "pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-gsl mingw-w64-x86_64-openmp" 
      - name: Build
        run: |
          # make a bin directory 
          # and build main.cpp in the ./src folder
          mkdir bin
          g++ -std=c++17 -v ${{github.workspace}}/src/*.cpp -o ${{github.workspace}}/bin/main.exe -l D:/mingw64/include -lgsl -lgslcblas -lm -fopenmp
      - name: Run
        run: |
          # run the program
          ${{github.workspace}}/bin/main.exe