name: Build C++ Program

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: msys2/setup-msys2@v2
      - name: Install Dependencies
        run: |
          msys2 -c "pacman -Qe"