name: Build C++ Program

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: msys2/setup-msys2@v2
      - name: Install Dependencies
        run: |
          # install GCC, GSL and OpenMP
          msys2 -c "pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-gsl mingw-w64-x86_64-openmp" 
      - name: Build
        run: |
          # build main.cpp in the ./src folder
          g++ -std=c++17 -o ./src/*.cpp -o ./src/main.exe -lgsl -lgslcblas -lm -fopenmp